### PR TITLE
MYR-000: CI/CD - Add new ENV variable

### PR DESCRIPTION
**Pull request by meziaris**
MYR-000: CI/CD - Add new ENV variable

### CODE REVIEW

**Comment by irmannmal** [comment]
@meziaris put new env variable to all pipeline

**Review by irmannmal — CHANGES_REQUESTED** [review]
Need to create new secret, and then don't forget to put it on Value.yaml

**Comment by meziaris** [comment]
> Need to create new secret, and then don't forget to put it on Value.yaml

Done.

**Comment by meziaris** [comment]
> @meziaris put new env variable to all pipeline

Done.

**Review by irmannmal — APPROVED** [review]

**Review by irmannmal — APPROVED** [review]

**Comment by meziaris** [comment]
> @meziaris put new env variable to all pipeline

Done.

**Pull request closed without merging**
